const e=React.createElement;
const I=({name,size=22})=>e('i',{'data-lucide':name,style:{width:size,height:size}});
const slides=[
 {title:'Project Phoenix',label:'Cover',type:'cover',notes:'Today’s update covers what Phase 1 delivered, the value already created, Phase 2 progress and the support required to maintain delivery momentum.'},
 {title:'Board update at a glance',label:'Executive summary',type:'summary',notes:'Phase 1 established the Salesforce foundation. Phase 2 extends that foundation into compliance, assets, repairs, scheduling and operational service delivery.'},
 {title:'Why change was needed',label:'Case for change',type:'why',notes:'Customer and service information was spread across systems, spreadsheets and manual processes, with limited tenant engagement, cost pressure, inflexibility and compliance risk.'},
 {title:'One platform. One customer view. Better services.',label:'Transformation vision',type:'vision',notes:'The objective was to establish one platform with a single customer view, consistent case management, connected communications, auditability, reporting and integrated delivery.'},
 {title:'What Phase 1 delivered',label:'Capabilities',type:'phase1',notes:'Phase 1 delivered visible service capabilities and the underlying platform controls required for safe, sustainable operation.'},
 {title:'Phase 1 milestones',label:'Delivery journey',type:'milestones',notes:'The programme progressed from testing and integration through deployment, go-live and managed support.'},
 {title:'Controlled delivery under pressure',label:'Challenges managed',type:'control',notes:'Complexity was managed through prioritisation, testing, escalation and formal change control—protecting quality and business confidence.'},
 {title:'Early Benefits Already Being Realised',label:'Business benefits',type:'benefits',notes:'Benefits will grow with adoption, but the platform is already improving visibility, case tracking, controls, auditability and reporting.'},
 {title:'Early Benefits Already Being Realised',label:'Benefits continued',type:'benefits2',notes:'The Salesforce platform also creates cloud, upgrade, internal capability, single source of truth, adoption and long-term digital transformation benefits.'},
 {title:'Operational performance visibility',label:'Executive dashboard',type:'dashboard',notes:'This is the executive reporting structure. Confirmed Salesforce exports should replace the placeholders before the Board meeting.'},
 {title:'Governance built into delivery',label:'Project governance',type:'governance',notes:'Governance maintained transparency, delivery assurance, risk and issue management, commercial control and operational readiness.'},
 {title:'The transformation journey',label:'Phase 1 to Phase 2',type:'journey',notes:'Phase 1 created the foundation. Phase 2 is now extending the platform into compliance and operational services.'},
 {title:'Phase 2: from scoping to delivery',label:'Roadmap',type:'roadmap',notes:'Phase 2 began with scoping in April and formal workshops on 11 June. The end of year 2026 target remains conditional on build, testing, integration and readiness.'},
 {title:'Compliance foundation built',label:'Achievements',type:'achievements',notes:'Alscient has completed the Health and Safety build, including Lifting Equipment, Legionella, Fire Safety and Gas Safety compliance functionality.'},
 {title:'Phase 2 scope status',label:'Delivery status',type:'scope',notes:'Compliance modules are built. Delivery focus now moves to the larger operational areas and readiness activity.'},
 {title:'Five priorities to reach go-live',label:'Remaining priorities',type:'priorities',notes:'The remaining priorities cover operational build, integration, testing and business readiness.'},
 {title:'Progress at a glance',label:'Achieved / remaining / target',type:'progress',notes:'Tangible progress has been made, but the next period is critical because the largest operational areas and readiness activities remain ahead.'},
 {title:'Lessons learned and continuous improvement',label:'Improvement approach',type:'lessons',notes:'Phase 2 is applying lessons from Phase 1 through earlier engagement, stronger change management, onsite discovery, requirements governance, improved UAT management, knowledge transfer and better documentation.'},
 {title:'Board support required',label:'Decision',type:'decision',notes:'Board support is required for delivery decisions, adoption, business readiness and continued treatment of Salesforce as a strategic organisational platform.'},
 {title:'Building the platform for CCHA’s future',label:'Close',type:'close',notes:'Phase 1 established the platform. Phase 2 is expanding its value. The focus now is disciplined delivery, readiness and sustained adoption.'}
];
const capability=[['contact-round','CRM','Customer 360 view'],['messages-square','General Enquiries','Consistent customer request handling'],['shield-alert','ASB','Structured ASB case management'],['message-square-warning','Complaints','More controlled complaints process'],['shield-check','Safeguarding','Safeguarding visibility and controls'],['plug-zap','Integrations','Open Housing to Salesforce · Five9 telephony contact centre with CRM']];
const statusRows=[['Health & Safety','Build completed','done'],['Lifting Equipment','Build completed','done'],['Legionella','Build completed','done'],['Fire Safety','Build completed','done'],['Gas Safety','Build completed','done'],['Asset Management (LifeSpan)','Pending delivery','pending'],['Repairs & Scheduling','Pending delivery','pending'],['Estate Services','Pending delivery','pending'],['Contractor Portal','Pending delivery','pending']];
function Shell({i,children,dark=false,kicker}){return e('section',{className:'slide enter '+(dark?'dark ':''),'data-slide':i},e('div',{className:'orb orb-a'}),e('div',{className:'orb orb-b'}),e('header',{className:'slide-head'},e('span',{className:'kicker'},kicker||slides[i].label),e('span',{className:'slide-count'},String(i+1).padStart(2,'0')+' / '+slides.length)),children,e('div',{className:'brandline'},e('span',{className:'brand-dot'}),'CCHA · PROJECT PHOENIX'))}
const Heading=({children,lead})=>e(React.Fragment,null,e('h2',null,children),lead&&e('p',{className:'lead'},lead));
const Card=({icon,title,text,tone='teal',className=''})=>e('article',{className:'vcard '+tone+' '+className},icon&&e('span',{className:'vicon'},e(I,{name:icon})),e('h3',null,title),text&&e('p',null,text));
function render(s,i){
 if(s.type==='cover')return e(Shell,{i,dark:true,kicker:'CCHA BOARD · JULY 2026'},e('div',{className:'cover-grid'},e('div',{className:'cover-copy'},e('div',{className:'live-pill'},e('span'),'BOARD UPDATE'),e('h1',null,'CCHA SalesForce',e('em',null,'Digital Transformation')),e('p',null,'Phase 1 delivery · Phase 2 progress · Strategic platform outlook'),e('div',{className:'cover-tags'},['Customer 360','Asset Management','Housing'].map((x,n)=>e('span',{key:x},e(I,{name:['users','building-2','home'][n],size:24}),x)))),e('div',{className:'platform-visual'},e('div',{className:'pv-core'},e(I,{name:'cloud',size:58}),e('b',null,'ONE CONNECTED',e('br'),'PLATFORM')),['Customer 360','Risk','Assets','Repairs','Insight'].map((x,n)=>e('span',{className:'sat sat-'+n,key:x},x)))));
 if(s.type==='summary')return e(Shell,{i},e(Heading,{lead:'The foundation is live. The operational transformation is underway.'},'Board update at a glance'),e('div',{className:'summary-grid'},[['check-circle-2','PHASE 1','Delivered','Core customer and case-management capabilities are in service.','green'],['blocks','PHASE 2','Building','Compliance build complete; remaining modules include Asset Management (LifeSpan), Repairs and Scheduling, and Contractor Portal.','amber'],['compass','DIRECTION','Strategic','Salesforce is becoming a core operational platform.','blue']].map(x=>e(Card,{key:x[1],icon:x[0],title:x[1]+' · '+x[2],text:x[3],tone:x[4]}))),e('div',{className:'message-ribbon'},e(I,{name:'arrow-up-right'}),e('b',null,'Foundation established'),e('span',null,'→'),e('b',null,'Compliance built'),e('span',null,'→'),e('b',null,'Operational modules remaining')));
 if(s.type==='why')return e(Shell,{i},e(Heading,{lead:'Important customer information was difficult to see, track, scale and act on.'},s.title),e('div',{className:'before-after why-expanded'},e('div',{className:'before-panel'},e('span',{className:'panel-label'},'BEFORE SALESFORCE'),[['files','Fragmented systems'],['eye-off','Limited visibility'],['handshake','Limited tenant engagement'],['badge-pound-sterling','High maintenance costs'],['scale','Inflexibility & scalability constraints'],['workflow','Operational inefficiencies'],['shield-alert','Compliance risks'],['mail-warning','Manual handovers']].map(x=>e('div',{className:'pain',key:x[1]},e(I,{name:x[0]}),e('span',null,x[1])))),e('div',{className:'bridge'},e(I,{name:'chevrons-right',size:38}),e('b',null,'Need for change')),e('div',{className:'after-panel'},e('span',{className:'panel-label'},'BUSINESS NEED'),e('div',{className:'need-core'},e(I,{name:'network',size:38}),e('strong',null,'Connected customer & case management')),e('div',{className:'mini-pills'},['Visibility','Scalability','Control'].map(x=>e('span',{key:x},x))))));
 if(s.type==='vision'){
  const nodes=[['contact-round','Single Customer View','Customer, household, tenancy and contact information in one place'],['folder-kanban','Case Management','Complaints, ASB, safeguarding and general enquiries managed consistently'],['mails','Connected Communications','Inbound and outbound emails captured against the customer record'],['file-check-2','Governance and Auditability','Clear ownership, activity history, case notes and audit trails'],['chart-no-axes-combined','Reporting and Oversight','Improved visibility of case volumes, performance and service demand'],['workflow','Integrated Delivery','Connecting Salesforce with Open Housing, Five9, MuleSoft and other systems']].map((x,n)=>e('div',{className:'vision-node vn-'+n,key:x[1]},e(I,{name:x[0]}),e('div',null,e('b',null,x[1]),e('small',null,x[2]))));
  const core=e('div',{className:'vision-core'},e(I,{name:'cloud-cog',size:46}),e('strong',null,'SALESFORCE'),e('small',null,'one platform'));
  const lines=e('svg',{className:'connector',viewBox:'0 0 900 360'},e('path',{d:'M450 180 L145 75 M450 180 L755 75 M450 180 L105 190 M450 180 L795 190 M450 180 L145 305 M450 180 L755 305'}));
  return e(Shell,{i,dark:true},e(Heading,{lead:'A reusable platform—not another isolated system.'},s.title),e('div',{className:'vision-map'},core,nodes,lines));
 }
 if(s.type==='phase1'){
  const cards=capability.map((x,n)=>e(Card,{key:x[1],icon:x[0],title:x[1],text:x[2],tone:['teal','green','blue','navy','amber'][n],className:'cap-'+n}));
  return e(Shell,{i},e(Heading,{lead:'Phase 1 established the CRM foundation and key service integrations.'},s.title),e('div',{className:'capability-grid'},cards));
 }
 if(s.type==='milestones')return e(Shell,{i},e(Heading,{lead:'A controlled path from test to live service.'},s.title),e('div',{className:'milestone-track'},[['Test','UAT signed off','ASB · General Enquiries · Safeguarding'],['Build','Complaints ready','Operational use'],['Connect','Integration complete','Open Housing data'],['Prepare','Production ready','Environments aligned'],['Launch','Go-live achieved','Live service'],['Support','Managed service','Support model established']].map((x,n)=>e('div',{className:'mile',key:x[0]},e('span',{className:'mile-num'},n+1),e(I,{name:['clipboard-check','blocks','plug','server-cog','rocket','life-buoy'][n]}),e('b',null,x[1]),e('small',null,x[2])))),e('div',{className:'success-strip'},e(I,{name:'badge-check'}),'Designed · tested · deployed · supported'));
 if(s.type==='control')return e(Shell,{i},e(Heading,{lead:'Pressure was real. Delivery remained governed.'},s.title),e('div',{className:'control-grid'},[['key-round','Pro2 licence delay','Alternative data and testing arrangements'],['git-compare-arrows','Integration complexity','Investigate · correct · replay'],['test-tubes','Extended UAT','Extended testing to protect quality'],['list-plus','Late requirements','Prioritised through change control'],['graduation-cap','Adoption concerns','Training · support · phased transition'],['scale','Budget & scope','Scope freeze · prioritisation · controls']].map(x=>e('article',{className:'control-card',key:x[1]},e('div',{className:'challenge-line'},e(I,{name:x[0]}),e('b',null,x[1])),e(I,{name:'arrow-down',size:18}),e('div',{className:'response-line'},x[2])))));
 if(s.type==='benefits')return e(Shell,{i},e(Heading,{lead:'Customer, case and control benefits from the Phase 1 foundation.'},s.title),e('div',{className:'benefit-list'},[['users','Improved visibility','of customer interactions across services'],['history','Better case tracking','with complete case history and ownership'],['shield-check','Stronger controls','for Safeguarding, ASB and Complaints'],['message-square-warning','Structured complaints','through standardised workflows'],['file-check-2','Improved audit trail','for compliance and accountability'],['chart-spline','Reporting foundation','with real-time operational insights'],['network','Less dependency','on manual and paper-based processes']].map((x,n)=>e('article',{className:'benefit-tile',key:x[1]},e(I,{name:x[0],size:28}),e('b',null,x[1]),e('small',null,x[2])))));
 if(s.type==='benefits2')return e(Shell,{i},e(Heading,{lead:'Platform benefits that reduce long-term technology risk and build internal capability.'},s.title),e('div',{className:'benefit-list benefit-list-continued'},[['cloud','Cloud-hosted platform','No infrastructure to maintain','Salesforce manages hosting, availability, security patches and upgrades'],['refresh-cw','Automatic upgrades','Continuous innovation','Three major releases every year without CCHA managing system upgrades or downtime planning'],['graduation-cap','Internal capability building','Upskilling our workforce','Trailhead and Trailblazer support Administrator, Business Analyst, Consultant and Developer skills'],['database','Single source of truth','Connected customer information','Customer, property and case information together in one CRM to improve decision-making and service delivery'],['rocket','Platform for digital transformation','Supporting better services for tenants','Reducing long-term technology risk while supporting better services'],['smile','Improved user adoption','Modern and intuitive experience','Easier navigation and consistent processes support productivity and reduce training effort']].map((x,n)=>e('article',{className:'benefit-tile benefit-tile-deep',key:x[1]},e(I,{name:x[0],size:28}),e('b',null,x[1]),e('strong',null,x[2]),e('small',null,x[3])))));
 if(s.type==='dashboard')return e(Shell,{i},e(Heading,{lead:'Validated operational insight—without inventing figures.'},s.title),e('div',{className:'dash-grid'},e('div',{className:'dash-main'},e('div',{className:'dash-toolbar'},e('b',null,'EXECUTIVE SALESFORCE DASHBOARD'),e('span',null,'LIVE DATA PLACEHOLDER')),e('div',{className:'chart-placeholder'},e(I,{name:'image',size:35}),e('b',null,'Insert exported dashboard screenshot'),e('small',null,'Cases created · cases resolved · complaints by status'))),e('div',{className:'dash-side'},['Total Cases Created','Total Cases Resolved','Complaints by Status'].map(x=>e('div',{className:'metric-card',key:x},e('span',null,x),e('b',null,'—'),e('small',null,'Insert confirmed figure'))))),e('div',{className:'adoption-callout'},e(I,{name:'activity'}),e('div',null,e('b',null,'Adoption dashboard installed'),e('small',null,'Active users · login trends · platform usage'))));
 if(s.type==='governance')return e(Shell,{i,dark:true},e(Heading,{lead:'Control applied across delivery, risk, cost and readiness.'},s.title),e('div',{className:'governance-map'},e('div',{className:'gov-core'},e(I,{name:'landmark',size:42}),e('b',null,'PROJECT',e('br'),'GOVERNANCE')), [['Delivery Assurance','Weekly programme reporting · milestone tracking · scope freeze before go-live','calendar-check'],['Risk & Issue Management','RAID log management · risk escalation · dependency tracking','triangle-alert'],['Commercial Control','Budget monitoring · change request governance · supplier oversight','badge-pound-sterling'],['Operational Readiness','Managed service transition · training and knowledge transfer · Phase 2 mobilisation','users-round']].map((x,n)=>e('div',{className:'gov-card gc-'+n,key:x[0]},e(I,{name:x[2]}),e('h3',null,x[0]),e('p',null,x[1])))));
 if(s.type==='journey')return e(Shell,{i},e(Heading,{lead:'Each stage unlocks the next layer of organisational value.'},s.title),e('div',{className:'journey-path'},[['01','PHASE 1','Foundation','Customer 360 · cases · safeguarding · integration','done'],['02','PHASE 2','Compliance','Health & Safety · lifting · legionella · fire · gas','done'],['03','PHASE 2','Operations','Assets · LifeSpan · repairs · scheduling · estates · contractor portal','active']].map(x=>e('article',{className:'journey-card '+x[4],key:x[0]},e('span',{className:'phase-num'},x[0]),e('small',null,x[1]),e('h3',null,x[2]),e('p',null,x[3]),e('span',{className:'journey-status'},x[4]==='done'?'DELIVERED':'IN DELIVERY')))),e('div',{className:'target-line'},e(I,{name:'flag'}),'Target outcome: broader operational transformation through Salesforce'));
 if(s.type==='roadmap')return e(Shell,{i},e(Heading,{lead:'Target go-live: end of year 2026—subject to readiness.'},s.title),e('div',{className:'roadmap-track'},[['APR','Scoping','April 2026','done'],['JUN','Workshops','11 June','done'],['JUN–SEP','Design & build','In progress','active'],['SEP–OCT','Testing & UAT','Planned','future'],['OCT–DEC','Training & readiness','Planned','future'],['END 2026','Target go-live','Conditional','target']].map((x,n)=>e('div',{className:'road-step '+x[3],key:x[0]+n},e('span',{className:'road-date'},x[0]),e('i'),e('b',null,x[1]),e('small',null,x[2])))),e('div',{className:'condition-box'},e(I,{name:'shield-alert'}),e('span',null,'Dependent on build, integration, testing, UAT and business readiness')));
 if(s.type==='achievements')return e(Shell,{i},e(Heading,{lead:'An important milestone for compliance visibility and auditability.'},s.title),e('div',{className:'compliance-grid'},[['heart-pulse','Health & Safety'],['lift','Lifting Equipment'],['droplets','Legionella'],['flame','Fire Safety'],['gauge','Gas Safety']].map((x,n)=>e('article',{className:'compliance-card',key:x[1],style:{'--delay':n}},e('span',{className:'check'},e(I,{name:'check'})),e(I,{name:x[0],size:30}),e('b',null,x[1]),e('small',null,'BUILD COMPLETED')))),e('div',{className:'foundation-banner'},e(I,{name:'shield-check'}),e('b',null,'COMPLIANCE FOUNDATION BUILT')));
 if(s.type==='scope')return e(Shell,{i},e(Heading,{lead:'Completed build is green; operational delivery remains amber.'},s.title),e('div',{className:'status-legend'},e('span',{className:'done'},'BUILD COMPLETED'),e('span',{className:'pending'},'PENDING DELIVERY'),e('span',{className:'test'},'TEST / UAT')),e('div',{className:'scope-table'},statusRows.map((x,n)=>e('div',{className:'scope-row',key:x[0]},e('span',{className:'scope-index'},String(n+1).padStart(2,'0')),e('b',null,x[0]),e('span',{className:'scope-status '+x[2]},e('i'),x[1])))));
 if(s.type==='priorities')return e(Shell,{i},e(Heading,{lead:'The shortest path to a controlled operational launch.'},s.title),e('div',{className:'priority-grid'},[['01','building-2','Asset Management (LifeSpan)','Assets · components · condition · lifecycle and replacement planning'],['02','calendar-clock','Repairs & Scheduling','Orders · appointments · operatives · schedules'],['03','trees','Estate Services','Cleaning · grounds · fly-tipping · services'],['04','clipboard-check','Testing & Readiness','UAT · training · data validation · go-live preparation']].map((x,n)=>e('article',{className:'priority p-'+n,key:x[0]},e('span',{className:'priority-num'},x[0]),e(I,{name:x[1],size:30}),e('h3',null,x[2]),e('p',null,x[3])))));
 if(s.type==='progress')return e(Shell,{i},e(Heading,{lead:'Good momentum. A critical delivery window remains.'},s.title),e('div',{className:'progress-columns'},e('article',{className:'progress-card achieved'},e('header',null,e(I,{name:'circle-check-big'}),'ACHIEVED'),e('ul',null,['Scoping commenced in April','Workshops began 11 June','Five compliance builds completed','Integration achieved','SharePoint integration achieved'].map(x=>e('li',{key:x},x)))),e('article',{className:'progress-card remaining'},e('header',null,e(I,{name:'circle-dot-dashed'}),'REMAINING'),e('ul',null,['Asset Management (LifeSpan)','Repairs, Scheduling & Estates','Contractor Portal','Data validation & UAT','Training and operational readiness'].map(x=>e('li',{key:x},x)))),e('article',{className:'progress-card target'},e('header',null,e(I,{name:'flag'}),'TARGET'),e('strong',null,'End of year',e('br'),'2026'),e('p',null,'Subject to successful delivery, testing and readiness.'))));
 if(s.type==='lessons')return e(Shell,{i},e(Heading,{lead:'Phase 2 is applying lessons from Phase 1 to strengthen delivery discipline and adoption.'},s.title),e('div',{className:'lessons-grid'},[['users-round','Earlier Business Engagement','Engage stakeholders earlier, secure management commitment and schedule workshops in advance.'],['presentation','Enhanced Training & Change Management','Start training earlier with multiple sessions, videos, user guides and hands-on practice.'],['map-pinned','Face-to-Face Discovery Sessions','Introduce onsite discovery workshops to validate requirements and improve collaboration.'],['clipboard-list','Requirements Governance','Use a central Requirements Tracker to capture, assess and prioritise requirements and change requests.'],['test-tube-2','Improved UAT Management','Improve test planning, prepare scenarios earlier and strengthen defect tracking and reporting.'],['graduation-cap','Knowledge Transfer & Internal Capability','Increase knowledge transfer and continue developing internal Salesforce capability through Trailhead and practical experience.'],['file-text','Improved Documentation & Traceability','Standardise documentation, decision logs and requirements traceability to improve transparency and future change management.']].map((x,n)=>e('article',{className:'lesson-card',key:x[1]},e(I,{name:x[0],size:24}),e('b',null,x[1]),e('small',null,e('strong',null,'Phase 2 Approach: '),x[2])))));
 if(s.type==='decision')return e(Shell,{i,dark:true},e(Heading,{lead:'A strategic platform requires organisational—not only ICT—sponsorship.'},s.title),e('div',{className:'decision-layout'},e('div',{className:'decision-list'},[['thumbs-up','Continue Phase 2 support'],['badge-pound-sterling','Govern budget & change'],['list-checks','Prioritise remaining scope'],['users','Champion adoption & readiness'],['landmark','Recognise Salesforce strategically']].map((x,n)=>e('button',{className:'decision-item',key:x[1],onClick:ev=>ev.currentTarget.classList.toggle('selected')},e('span',null,String(n+1).padStart(2,'0')),e(I,{name:x[0]}),e('b',null,x[1]),e(I,{name:'check-circle-2'})))),e('div',{className:'board-question'},e(I,{name:'message-circle-question',size:36}),e('small',null,'BOARD DISCUSSION'),e('h3',null,'Does the Board endorse Salesforce as CCHA’s strategic platform for operational transformation?'),e('span',null,'Click each support item to mark discussion complete'))));
 return e(Shell,{i,dark:true,kicker:'CLOSING MESSAGE'},e('div',{className:'close-wrap'},e('span',{className:'closing-icon'},e(I,{name:'sunrise',size:44})),e('h2',null,'Building the platform for',e('em',null,'CCHA’s future')),e('p',null,'Salesforce is becoming CCHA’s strategic platform for customer visibility, operational control, compliance, reporting and future digital service delivery.'),e('div',{className:'closing-steps'},[['check','Foundation delivered'],['loader-circle','Transformation in progress'],['handshake','Board support sustains momentum']].map(x=>e('span',{key:x[1]},e(I,{name:x[0]}),x[1])))));
}
function App(){const[idx,setIdx]=React.useState(0),[notes,setNotes]=React.useState(false),[busy,setBusy]=React.useState(false),[presenting,setPresenting]=React.useState(false),[menu,setMenu]=React.useState(false);const slideRef=React.useRef(null),appRef=React.useRef(null);
 const go=n=>setIdx(Math.max(0,Math.min(slides.length-1,n)));
 async function togglePresent(){try{if(!document.fullscreenElement){await appRef.current.requestFullscreen();setNotes(false)}else await document.exitFullscreen()}catch(_){setPresenting(v=>!v)}}
 React.useEffect(()=>{const sync=()=>setPresenting(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',sync);const k=x=>{if(['ArrowRight','PageDown',' '].includes(x.key)){x.preventDefault();go(idx+1)}if(['ArrowLeft','PageUp'].includes(x.key))go(idx-1);if(x.key.toLowerCase()==='n')setNotes(v=>!v);if(x.key.toLowerCase()==='f')togglePresent();if(x.key==='Escape'&&presenting)setPresenting(false);if(x.key==='Home')go(0);if(x.key==='End')go(slides.length-1)};addEventListener('keydown',k);return()=>{removeEventListener('keydown',k);document.removeEventListener('fullscreenchange',sync)}},[idx,presenting]);
 React.useEffect(()=>{if(window.lucide)window.lucide.createIcons();},[idx,notes,menu]);
 async function capture(n){go(n);await new Promise(r=>setTimeout(r,450));return html2canvas(slideRef.current,{scale:1.5,useCORS:true,backgroundColor:'#f5f7f8'});}
 async function exportPDF(){setBusy(true);try{const pdf=new jspdf.jsPDF({orientation:'landscape',unit:'px',format:[1280,720]});for(let n=0;n<slides.length;n++){const c=await capture(n);if(n)pdf.addPage([1280,720],'landscape');pdf.addImage(c.toDataURL('image/jpeg',.93),'JPEG',0,0,1280,720)}pdf.save('project-phoenix-board-update.pdf')}finally{setBusy(false)}}
 async function exportPPT(){setBusy(true);try{const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author='CCHA';pptx.title='Project Phoenix: Salesforce Transformation Board Update';for(let n=0;n<slides.length;n++){const c=await capture(n),p=pptx.addSlide();p.addImage({data:c.toDataURL('image/png'),x:0,y:0,w:13.333,h:7.5});p.addNotes(slides[n].notes)}await pptx.writeFile({fileName:'project-phoenix-board-update.pptx'})}finally{setBusy(false)}}
 return e('div',{className:'app '+(presenting?'presenting':''),ref:appRef},e('header',{className:'topbar'},e('button',{className:'brand',onClick:()=>go(0)},e('span',{className:'brand-mark'},'P'),e('span',null,e('b',null,'PROJECT PHOENIX'),e('small',null,'CCHA BOARD UPDATE'))),e('nav',{className:'actions'},e('button',{className:'tool primary',onClick:togglePresent},e(I,{name:'presentation',size:17}),presenting?'Exit':'Present'),e('button',{className:'tool',onClick:()=>setMenu(!menu)},e(I,{name:'layout-grid',size:17}),'Overview'),e('button',{className:'tool',onClick:()=>setNotes(!notes)},e(I,{name:'notebook-tabs',size:17}),'Notes'),e('div',{className:'export-menu'},e('button',{className:'tool'},e(I,{name:'download',size:17}),'Export'),e('div',{className:'export-pop'},e('button',{onClick:()=>window.print()},'Print / Save PDF'),e('button',{disabled:busy,onClick:exportPDF},'Download PDF'),e('button',{disabled:busy,onClick:exportPPT},'Download PPTX'))))),e('div',{className:'workspace'},e('aside',{className:'rail'},slides.map((s,n)=>e('button',{className:'rail-item '+(n===idx?'active':''),onClick:()=>go(n),key:s.title},e('span',null,String(n+1).padStart(2,'0')),e('div',null,e('b',null,s.title),e('small',null,s.label))))),e('main',{className:'stage'},e('div',{className:'slide-frame',ref:slideRef,key:idx},render(slides[idx],idx)),notes&&e('aside',{className:'notes-panel'},e('header',null,e(I,{name:'mic-2'}),e('b',null,'SPEAKER NOTE'),e('button',{onClick:()=>setNotes(false)},'×')),e('p',null,slides[idx].notes))),e('footer',{className:'controls'},e('button',{disabled:idx===0,onClick:()=>go(idx-1)},e(I,{name:'arrow-left'}),'Previous'),e('div',{className:'track'},e('i',{style:{width:`${(idx+1)/slides.length*100}%`}})),e('span',null,`${idx+1} / ${slides.length}`),e('button',{disabled:idx===slides.length-1,onClick:()=>go(idx+1)},'Next',e(I,{name:'arrow-right'})))),menu&&e('div',{className:'overview',onClick:()=>setMenu(false)},e('div',{className:'overview-panel',onClick:x=>x.stopPropagation()},e('header',null,e('div',null,e('small',null,'INTERACTIVE AGENDA'),e('h3',null,'Board update overview')),e('button',{onClick:()=>setMenu(false)},'×')),e('div',{className:'overview-grid'},slides.map((s,n)=>e('button',{onClick:()=>{go(n);setMenu(false)},className:n===idx?'current':'',key:s.title},e('span',null,String(n+1).padStart(2,'0')),e(I,{name:['home','scan-line','circle-help','network','blocks','milestone','shield-alert','sparkles','cloud','chart-no-axes-combined','tower-control','route','calendar-range','shield-check','list-checks','flag','gauge','refresh-cw','vote','sunrise'][n]||'circle'}),e('b',null,s.title),e('small',null,s.label)))))));
}
ReactDOM.createRoot(document.getElementById('root')).render(e(App));
