const e=React.createElement;
const slides=[
 {title:'Project Phoenix: Salesforce Transformation Board Update',type:'cover',sub:'Phase 1 foundation. Phase 2 operational transformation.',notes:'Today’s update covers the Phase 1 foundation, the progress made in Phase 2 and the support required to maintain delivery momentum.'},
 {title:'Foundation delivered. Operational transformation in progress.',type:'snapshot',notes:'Phase 1 is live and transitioned into service. Phase 2 is building on that foundation. The October date remains conditional on delivery and readiness.'},
 {title:'Why change was needed',type:'why',notes:'Before Salesforce, customer and service information was fragmented across systems, spreadsheets and manual processes, limiting visibility and consistent case management.'},
 {title:'One connected platform',type:'hub',notes:'The objective was broader than replacing processes: establish one platform for customer visibility, case management, safeguarding, auditability and reporting.'},
 {title:'Phase 1 established the foundation',type:'foundation',notes:'Phase 1 delivered customer-facing capabilities and the security, integration and support controls needed for sustainable operation.'},
 {title:'Phase 1 delivery milestones',type:'milestones',notes:'The programme progressed from UAT and integration through production deployment, go-live and managed support.'},
 {title:'Controlled delivery under pressure',type:'control',notes:'Challenges were managed through prioritisation, testing, escalation and formal change control, protecting quality and business confidence.'},
 {title:'Value created with transparent control',type:'value',notes:'Benefits are already visible in interaction history, case tracking, safeguarding controls and auditability, supported by disciplined governance.'},
 {title:'The transformation journey',type:'journey',notes:'Phase 1 established the Salesforce foundation. Phase 2 extends it into compliance, assets, repairs, scheduling and operational service delivery.'},
 {title:'Phase 2: from scoping to delivery',type:'roadmap',notes:'Phase 2 began with scoping activities in April, with formal workshops commencing on 11 June. Subject to build, testing, integration and business readiness, go-live is targeted for the third week of October.'},
 {title:'Phase 2 status',type:'status',notes:'Alscient has completed the Health and Safety build, including Lifting Equipment, Legionella, Fire Safety and Gas Safety. Focus now moves to Asset Management, LifeSpan, Repairs and Scheduling, and Estate Services.'},
 {title:'Operational performance visibility',type:'dashboard',notes:'This slide is ready for confirmed Salesforce dashboard exports. No figures are shown until validated.'},
 {title:'Board support required',type:'decision',notes:'The Board’s support is required for delivery decisions, adoption, business readiness and continued treatment of Salesforce as a strategic organisational platform.'}
];
const icons={customer:'C',risk:'R',communication:'M',security:'S',integration:'I'};
function Base({i,children,dark=false}){return e('section',{className:'slide'+(dark?' dark':''),'data-slide':i},e('div',{className:'eyebrow'},'CCHA BOARD | JULY 2026'),children,e('div',{className:'page-number'},String(i+1).padStart(2,'0')))}
function renderSlide(s,i){
 if(s.type==='cover')return e(Base,{i,dark:true},e('div',{className:'hero-accent'}),e('h1',null,'Project Phoenix:',e('br'),'Salesforce Transformation',e('br'),'Board Update'),e('p',{className:'subtitle'},s.sub),e('div',{className:'status blue'},'CCHA BOARD • JULY 2026'));
 if(s.type==='snapshot')return e(Base,{i},e('h2',null,s.title),e('div',{className:'cards three'},[['PHASE 1','LIVE','green'],['PHASE 2','BUILDING','amber'],['PLATFORM','STRATEGIC','blue']].map((x,n)=>e('div',{className:'card',key:n},e('div',{className:'icon'},'0'+(n+1)),e('h3',null,x[0]),e('div',{className:'status '+x[2]},x[1])))),e('div',{className:'status amber'},'Target: third week of October 2026 — subject to readiness'));
 if(s.type==='why')return e(Base,{i},e('h2',null,s.title),e('div',{className:'flow'},['Fragmented systems','→','Limited visibility','→','Manual handovers','→','Reporting gaps'].map((x,n)=>x==='→'?e('div',{className:'arrow',key:n},x):e('div',{className:'flow-node',key:n},x))));
 if(s.type==='hub')return e(Base,{i},e('h2',null,s.title),e('div',{className:'hub'},e('div',{className:'hub-core'},'SALESFORCE',e('br'),'PLATFORM'),['Customer 360','Case management','Safeguarding','Audit trail','Reporting'].map((x,n)=>e('div',{className:'hub-node n'+(n+1),key:x},x))));
 if(s.type==='foundation')return e(Base,{i},e('h2',null,s.title),e('div',{className:'cards five'},[['customer','Customer & cases','Customer 360 • General Enquiries • Complaints'],['risk','Risk & safeguarding','ASB • red flags • diary notes'],['communication','Communications','Email templates • interaction history'],['security','Security','Access model • production controls'],['integration','Integration & support','Open Housing • managed service']].map(x=>e('div',{className:'card',key:x[0]},e('div',{className:'icon'},icons[x[0]]),e('h3',null,x[1]),e('p',null,x[2])))));
 if(s.type==='milestones')return e(Base,{i},e('h2',null,s.title),e('div',{className:'timeline'},['UAT signed off','Complaints ready','Integration complete','Production ready','Go-live','Managed service'].map(x=>e('div',{className:'milestone',key:x},e('i',{className:'dot'}),e('b',null,x)))),e('div',{className:'status green'},'Designed • tested • deployed • supported'));
 if(s.type==='control')return e(Base,{i},e('h2',null,s.title),e('div',{className:'matrix'},[['Licence delay','Alternative testing'],['Integration complexity','Correct & replay'],['Extended UAT','Protect quality'],['Scope & budget','Formal change control']].flatMap((x,n)=>[e('div',{className:'challenge',key:'c'+n},x[0]),e('div',{className:'arrow',key:'a'+n},'→'),e('div',{className:'response',key:'r'+n},x[1])])));
 if(s.type==='value')return e(Base,{i},e('h2',null,s.title),e('div',{className:'cards four'},[['Customer','Clearer interactions'],['Risk','Stronger safeguarding'],['Operations','Better case tracking'],['Governance','Stronger audit trail']].map(x=>e('div',{className:'card',key:x[0]},e('h3',null,x[0]),e('p',null,x[1])))),e('div',{className:'status blue'},'Weekly reporting • RAID • budget • change control'));
 if(s.type==='journey')return e(Base,{i},e('h2',null,s.title),e('div',{className:'journey'},[['01','FOUNDATION','Delivered','complete'],['02','COMPLIANCE','Build complete','complete'],['03','OPERATIONS','In delivery','pending']].map(x=>e('div',{className:'stage-card '+x[3],key:x[0]},e('div',{className:'num'},x[0]),e('h3',null,x[1]),e('p',null,x[2])))),e('div',{className:'status blue'},'→ Broader operational transformation'));
 if(s.type==='roadmap')return e(Base,{i},e('h2',null,s.title),e('div',{className:'timeline'},[['April','Scoping'],['11 June','Workshops'],['Jun–Sep','Build'],['Sep–Oct','Test / UAT'],['October','Readiness'],['3rd week','Target']].map((x,n)=>e('div',{className:'milestone',key:x[0]},e('i',{className:'dot',style:{background:n<3?'var(--green)':n===5?'var(--amber)':'var(--blue)'}}),e('b',null,x[0]),e('small',null,x[1])))),e('p',{className:'subtitle',style:{fontSize:'14px'}},'Target go-live remains the third week of October 2026, subject to successful completion of build, integration, testing, UAT and business-readiness activities.'));
 if(s.type==='status')return e(Base,{i},e('h2',null,s.title),e('div',{className:'status-board'},[['complete','COMPLETED',['Health & Safety','Lifting Equipment','Legionella','Fire Safety','Gas Safety']],['delivery','IN DELIVERY',['Asset Management','LifeSpan','Repairs & Scheduling','Estate Services']],['next','NEXT GATE',['Integration / data validation','System testing / UAT','Training / readiness']]].map(x=>e('div',{className:'status-col '+x[0],key:x[0]},e('header',null,x[1]),e('ul',null,x[2].map(y=>e('li',{key:y},y)))))));
 if(s.type==='dashboard')return e(Base,{i},e('h2',null,s.title),e('div',{className:'dashboard-placeholder'},'INSERT EXPORTED SALESFORCE DASHBOARD'),e('div',{className:'metric-row'},['Cases created','Cases resolved','Open cases','Active users','Tickets resolved','Compliance modules'].map(x=>e('div',{className:'metric',key:x},e('b',null,x),e('span',null,'Insert confirmed figure')))));
 return e(Base,{i,dark:true},e('div',{className:'question'},'Does the Board endorse Salesforce as CCHA’s strategic platform for operational transformation?'),e('div',{className:'decision-chips'},['Sustain Phase 2','Govern budget / change','Prioritise scope','Champion adoption','Treat Salesforce strategically'].map(x=>e('span',{key:x},x))),e('p',{className:'subtitle'},'Foundation delivered • Transformation in progress • Board support sustains momentum'));
}
function App(){const[idx,setIdx]=React.useState(0),[notes,setNotes]=React.useState(false),[busy,setBusy]=React.useState(false),[presenting,setPresenting]=React.useState(false);const slideRef=React.useRef(null),appRef=React.useRef(null);
 async function togglePresent(){if(!document.fullscreenElement){await appRef.current.requestFullscreen();setNotes(false)}else{await document.exitFullscreen()}}
 React.useEffect(()=>{const sync=()=>setPresenting(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',sync);const k=x=>{if(x.key==='ArrowRight'||x.key==='PageDown'||x.key===' ')setIdx(v=>Math.min(slides.length-1,v+1));if(x.key==='ArrowLeft'||x.key==='PageUp')setIdx(v=>Math.max(0,v-1));if(x.key.toLowerCase()==='n')setNotes(v=>!v);if(x.key.toLowerCase()==='f')togglePresent();if(x.key==='Home')setIdx(0);if(x.key==='End')setIdx(slides.length-1)};addEventListener('keydown',k);return()=>{removeEventListener('keydown',k);document.removeEventListener('fullscreenchange',sync)}},[]);
 async function capture(i){setIdx(i);await new Promise(r=>setTimeout(r,180));return html2canvas(slideRef.current,{scale:1.5,useCORS:true,backgroundColor:'#f7f8f6'});}
 async function exportPDF(){setBusy(true);try{const pdf=new jspdf.jsPDF({orientation:'landscape',unit:'px',format:[1280,720]});for(let i=0;i<slides.length;i++){const c=await capture(i);if(i)pdf.addPage([1280,720],'landscape');pdf.addImage(c.toDataURL('image/jpeg',.92),'JPEG',0,0,1280,720)}pdf.save('project-phoenix-board-update.pdf')}finally{setBusy(false)}}
 async function exportPPT(){setBusy(true);try{const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author='CCHA';pptx.subject='Project Phoenix Board Update';pptx.title='Project Phoenix: Salesforce Transformation Board Update';for(let i=0;i<slides.length;i++){const c=await capture(i);const p=pptx.addSlide();p.background={color:'F7F8F6'};p.addImage({data:c.toDataURL('image/png'),x:0,y:0,w:13.333,h:7.5});p.addNotes(slides[i].notes)}await pptx.writeFile({fileName:'project-phoenix-board-update.pptx'})}finally{setBusy(false)}}
 function printPDF(){window.print()}
 return e('div',{className:'app'+(presenting?' presenting':''),ref:appRef},e('header',{className:'topbar'},e('div',{className:'brand'},e('div',{className:'brand-mark'},'C'),e('div',null,e('b',null,'Project Phoenix'),e('small',null,'CCHA Board Presentation'))),e('div',{className:'actions'},e('button',{className:'btn primary',onClick:togglePresent},presenting?'Exit presentation':'Present'),e('button',{className:'btn',onClick:()=>setNotes(!notes)},notes?'Hide notes':'Speaker notes'),e('button',{className:'btn',onClick:printPDF},'Print / PDF'),e('button',{className:'btn',disabled:busy,onClick:exportPDF},busy?'Exporting...':'Download PDF'),e('button',{className:'btn',disabled:busy,onClick:exportPPT},busy?'Exporting...':'Download PPTX'))),e('div',{className:'viewport'},e('aside',{className:'sidebar'},slides.map((s,i)=>e('button',{className:'thumb '+(idx===i?'active':''),onClick:()=>setIdx(i),key:s.title},e('b',null,String(i+1).padStart(2,'0')+'  '+s.title),e('span',null,s.type.toUpperCase())))),e('main',{className:'stage'},e('div',{ref:slideRef},renderSlide(slides[idx],idx),notes&&e('div',{className:'notes-panel'},e('b',null,'Speaker note'),e('br'),slides[idx].notes)))),e('footer',{className:'footerbar'},e('button',{className:'navbtn',disabled:idx===0,onClick:()=>setIdx(idx-1)},'Previous'),e('div',{className:'progress'},e('i',{style:{width:((idx+1)/slides.length*100)+'%'}})),e('span',{className:'counter'},(idx+1)+' / '+slides.length),e('button',{className:'navbtn',disabled:idx===slides.length-1,onClick:()=>setIdx(idx+1)},'Next')))}
ReactDOM.createRoot(document.getElementById('root')).render(e(App));
